apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: t74rg8bl2-go-gitops
  description: This is GitOps manifest for t74rg8bl2-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=t74rg8bl2-go
    backstage.io/kubernetes-id: t74rg8bl2-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: t74rg8bl2-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:t74rg8bl2-go
